steps:
  - name: 'python:3.12'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "$SERVICE_ACCOUNT_KEY" > key.json
        export GOOGLE_APPLICATION_CREDENTIALS="key.json"

        pip install -r requirements.txt

        # batch_index を Pub/Sub メッセージから取り出す
        BATCH_INDEX=$(echo "$BUILD_EVENT_JSON" | grep -o '"batch_index": *[0-9]*' | grep -o '[0-9]*')
        echo "実行バッチ: $BATCH_INDEX"
        python main.py --batch_index=$BATCH_INDEX

timeout: '1800s'

availableSecrets:
  secretManager:
    - versionName: projects/hogeticlab-legs-prd/secrets/SERVICE_ACCOUNT_KEY/versions/latest
      env: SERVICE_ACCOUNT_KEY
