steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/pixiv-middle-class-ip-name-info/scraper-image:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/pixiv-middle-class-ip-name-info/scraper-image:latest']

  # Cloud Run Jobとしてデプロイし、Pub/Subトリガーを設定
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'pixiv-middle-class-ip-name-info-job'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/pixiv-middle-class-ip-name-info/scraper-image:latest'
      - '--region'
      - 'asia-northeast1'
      - '--service-account'
      - 'hogeticlab-legs-prd@appspot.gserviceaccount.com'
      - '--task-timeout=86400'
      - '--memory=1Gi'
      - '--max-retries=0'
      # このジョブを起動するPub/Subトピックを指定
      - '--set-pubsub-trigger=projects/$PROJECT_ID/topics/run-scraper-topic'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/pixiv-middle-class-ip-name-info/scraper-image:latest'
timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
