steps:
  # 1. Dockerイメージをビルド
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/pixiv-middle-class-ip-name-info/pixiv_scraping_image:$COMMIT_SHA'
    - '.'

  # 2. ビルドしたイメージをArtifact Registryにプッシュ
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/pixiv-middle-class-ip-name-info/pixiv_scraping_image:$COMMIT_SHA'

# ビルド成果物としてイメージを登録
images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/pixiv-middle-class-ip-name-info/pixiv_scraping_image:$COMMIT_SHA'

# タイムアウト設定 (24時間）
timeout: '86400s'

options:
  logging: CLOUD_LOGGING_ONLY