steps:
  # ステップ1: 必要なライブラリをインストールする
  - name: 'python:3.12'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt', '--user']

  # ステップ2: Pythonスクリプトを実行する
  - name: 'python:3.12'
    entrypoint: 'python'
    args:
      - 'main.py'
      # Pub/Subメッセージからバッチ番号を取り出して引数として渡す
      # デフォルトは0
      - '--batch_index'
      - $(body.message.data.batch_index)

# ビルド全体のタイムアウトを24時間に設定
timeout: '86400s'

options:
  logging: CLOUD_LOGGING_ONLY
